services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: trace-thermal-risk-engine

    restart: unless-stopped

    environment:
      POSTGRES_DB: fire_intelligence
      POSTGRES_USER: fire_admin
      POSTGRES_PASSWORD: 131006

    ports:  
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: