-- Deprecated: thermal_anomalies has one canonical definition in schema.sql.
-- Do not execute this file. The former raw-feed definition used names such as
-- acq_date, bright_ti4, and geometry that are incompatible with the
-- normalized application contract.